name: CombatEnhanced
version: ${project.version}
main: io.github.rickyc0626.cbe.CombatEnhanced
api-version: 1.15
authors: [ RickyC0626 ]
description: Enhanced player movement, weapon mechanics, custom enchantments
commands:
    cbe:
        description: Main command for CombatEnhanced
        permission: cbe.main
        usage: "Usage: /cbe help"